pub(crate) const SKY130_DRC_RULES_PATH: &str =
    "/tools/commercial/skywater/swtech130/skywater-src-nda/s8/V2.0.1/DRC/Calibre/s8_drcRules";
pub(crate) const SKY130_DRC_RUNSET_PATH: &str = "/tools/B/rahulkumar/sky130/priv/drc/runset";
pub(crate) const SKY130_LAYERPROPS_PATH: &str = "/tools/C/ethanwu10/sky130/nda/sky130.layerprops";
pub(crate) const SKY130_LVS_RULES_PATH: &str =
    "/tools/commercial/skywater/swtech130/skywater-src-nda/s8/V2.0.1/LVS/Calibre/lvs_s8_opts";
pub(crate) const SKY130_PEX_RULES_PATH: &str =
    "/tools/commercial/skywater/swtech130/skywater-src-nda/s8/V2.0.1/PEX/xRC/xrcControlFile_s8";

use crate::schematic::FromParams;
use arcstr::ArcStr;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use substrate::context::Context;
use substrate::schematic::Schematic;

/// Inputs to extraction. Its source netlist is always generated by Substrate 2.
pub struct PexInput {
    pub work_dir: PathBuf,
    pub layout_path: PathBuf,
    pub layout_cell_name: ArcStr,
    pub source_paths: Vec<PathBuf>,
    pub source_cell_name: ArcStr,
    pub pex_netlist_path: PathBuf,
    pub opts: HashMap<ArcStr, ArcStr>,
    pub ground_net: String,
}
#[derive(Debug, PartialEq, Eq)]
pub enum DrcSummary {
    Pass,
    Fail,
}
pub struct DrcOutput {
    pub summary: DrcSummary,
}
#[derive(Debug, PartialEq, Eq)]
pub enum LvsSummary {
    Pass,
    Fail,
}
pub struct LvsOutput {
    pub summary: LvsSummary,
}

/// Physical verification uses Calibre directly, with legacy geometry and native schematics.
pub trait CalibreContext {
    fn write_drc<B: substrate1::component::Component>(
        &self,
        params: &B::Params,
        work_dir: impl AsRef<Path>,
    ) -> anyhow::Result<DrcOutput>;
    fn write_lvs<B>(
        &self,
        params: &<B as FromParams>::Params,
        work_dir: impl AsRef<Path>,
    ) -> anyhow::Result<LvsOutput>
    where
        B: Schematic<Schema = sky130::Sky130>
            + FromParams
            + substrate1::component::Component<Params = <B as FromParams>::Params>;
    fn run_pex(&self, input: PexInput) -> anyhow::Result<calibre::pex::PexData>;
}
impl CalibreContext for Context {
    fn write_drc<B: substrate1::component::Component>(
        &self,
        params: &B::Params,
        work_dir: impl AsRef<Path>,
    ) -> anyhow::Result<DrcOutput> {
        let layout = crate::layout_ctx();
        let path = work_dir.as_ref().join("layout.gds");
        layout.write_layout::<B>(params, &path)?;
        let name = B::new(params, &layout)?.name();
        let data = calibre::drc::run_drc(&calibre::drc::DrcParams {
            cell_name: &name,
            work_dir: work_dir.as_ref(),
            layout_path: &path,
            rules_path: Path::new(SKY130_DRC_RULES_PATH),
            runset_path: Some(Path::new(SKY130_DRC_RUNSET_PATH)),
            layerprops: Some(Path::new(SKY130_LAYERPROPS_PATH)),
        })?;
        Ok(DrcOutput {
            summary: if data.rule_checks.iter().all(|c| c.num_results == 0) {
                DrcSummary::Pass
            } else {
                DrcSummary::Fail
            },
        })
    }
    fn write_lvs<B>(
        &self,
        params: &<B as FromParams>::Params,
        work_dir: impl AsRef<Path>,
    ) -> anyhow::Result<LvsOutput>
    where
        B: Schematic<Schema = sky130::Sky130>
            + FromParams
            + substrate1::component::Component<Params = <B as FromParams>::Params>,
    {
        let layout = crate::layout_ctx();
        let path = work_dir.as_ref().join("layout.gds");
        let source = work_dir.as_ref().join("schematic.spice");
        layout.write_layout::<B>(params, &path)?;
        crate::netlist::write_schematic::<B>(self, params, &source)?;
        let name = substrate::block::Block::name(&B::from_params(params)?);
        let data = calibre::lvs::run_lvs(&calibre::lvs::LvsParams {
            work_dir: work_dir.as_ref(),
            layout_path: &path,
            layout_cell_name: &name,
            source_paths: &[source],
            source_cell_name: &name,
            rules_path: Path::new(SKY130_LVS_RULES_PATH),
            layerprops: Some(Path::new(SKY130_LAYERPROPS_PATH)),
        })?;
        Ok(LvsOutput {
            summary: if data.status == calibre::lvs::LvsStatus::Correct {
                LvsSummary::Pass
            } else {
                LvsSummary::Fail
            },
        })
    }
    fn run_pex(&self, input: PexInput) -> anyhow::Result<calibre::pex::PexData> {
        let level = match input.opts.get("level").map(|s| s.as_str()).unwrap_or("rcc") {
            "r" => calibre::pex::PexLevel::R,
            "c" => calibre::pex::PexLevel::C,
            "rc" => calibre::pex::PexLevel::Rc,
            "rcc" => calibre::pex::PexLevel::Rcc,
            other => anyhow::bail!("unsupported extraction level {other}"),
        };
        let output = calibre::pex::run_pex(&calibre::pex::PexParams {
            work_dir: &input.work_dir,
            layout_path: &input.layout_path,
            layout_cell_name: &input.layout_cell_name,
            source_paths: &input.source_paths,
            source_cell_name: &input.source_cell_name,
            rules_path: Path::new(SKY130_PEX_RULES_PATH),
            pex_netlist_path: &input.pex_netlist_path,
            ground_net: &input.ground_net,
            level,
            defines: &[],
        })?;
        anyhow::ensure!(
            output.status == calibre::lvs::LvsStatus::Correct,
            "PEX LVS failed"
        );
        anyhow::ensure!(
            input.pex_netlist_path.is_file(),
            "PEX did not produce {}",
            input.pex_netlist_path.display()
        );
        Ok(output)
    }
}
